// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yibi.Repositories.MySql;

namespace Yibi.Repositories.MySql.SGroupMigrations
{
    [DbContext(typeof(MySqlContext))]
    [Migration("20190920082827_SGroupMigrations002")]
    partial class SGroupMigrations002
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Yibi.Core.Entities.ResourceGroupAccountInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccountPassword");

                    b.Property<string>("AllowUsers");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("EntryPoint");

                    b.Property<string>("Environment");

                    b.Property<DateTime>("LastUpdatedDate");

                    b.Property<string>("TypeName");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("ResourceGroupAccount");
                });

            modelBuilder.Entity("Yibi.Core.Entities.TypeNameInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("LastUpdatedDate");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("TypeNames");
                });
#pragma warning restore 612, 618
        }
    }
}
