// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yibi.Repositories.MySql;

namespace Yibi.Repositories.MySql.DingtalkMigrations
{
    [DbContext(typeof(MySqlContext))]
    partial class MySqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Yibi.Core.Entities.StaffInfo", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256);

                    b.Property<string>("DepmtId");

                    b.Property<string>("DepmtName");

                    b.Property<string>("Email");

                    b.Property<bool>("IsLeader");

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("Phone");

                    b.Property<string>("StaffNumber");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Staff");
                });
#pragma warning restore 612, 618
        }
    }
}
